apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: webflux-grpc
  annotations:
    github.com/project-slug: vkoppara/webflux-grpc
spec:
 type: service
  lifecycle: experimental
  owner: group:pet-managers
  providesApis:
    - petstore
    - internal/streetlights
    - hello-world
