apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: webflux-grpc
  annotations:
    github.com/project-slug: vkoppara/webflux-grpc
spec:
  type: service
  lifecycle: experimental
  owner: guests
  providesApis:
    - batch-commandline
